### ISSUE TITLE
what the fuck is this (HELP MEEEEEE)

### ISSUE THREAD

**Issue by coderinacoolway** [ThatRozebudDude/FPS-Plus-Public#106]
![image](https://github.com/user-attachments/assets/2d13a889-e860-4e2f-b795-bb6e03a4a68b)

**Comment by ThatRozebudDude** [comment]
You should be using `hmm` to install the correct version of all the libraries. Read through the [building section of the readme](https://github.com/ThatRozebudDude/FPS-Plus-Public?tab=readme-ov-file#building) and follow the instructions there, hopefully it should fix the issue.

**Comment by coderinacoolway** [comment]
ily

**Comment by ThatRozebudDude** [comment]
Also just letting you know, you were using an almost 3 year old version of Flixel, you should probably update some of your libraries in general.

**Comment by coderinacoolway** [comment]
I mostly compile psych so yeah they are pretty old what do versions do you recommend me to update to?

**Comment by coderinacoolway** [comment]
![image](https://github.com/user-attachments/assets/ff0a2f19-4fa7-4669-976e-0a7586674e6f)
I am indeed getting errors is it because of the libraries

**Comment by ThatRozebudDude** [comment]
Is your Haxe up to date?

**Comment by coderinacoolway** [comment]
is up to date just the latest

**Comment by ThatRozebudDude** [comment]
Yes

**Comment by coderinacoolway** [comment]
![image](https://github.com/user-attachments/assets/46083ee7-4452-4fd1-b64a-b9d89b1d5a03)
hm

**Comment by ThatRozebudDude** [comment]
[Check this.](https://github.com/ThatRozebudDude/FPS-Plus-Public/issues/91) There is a bug in haxelib that causes certain types of libraries to to not work right with local libraries so you also need to have the correct version of `hxCodec` globally to compile.

**Comment by coderinacoolway** [comment]
thank you it is compiling now
