### ISSUE TITLE
Auto Complete events or whatever

### ISSUE THREAD

**Issue by UnknownSkid** [ThatRozebudDude/FPS-Plus-Public#108]
like in minecraft when you type a command it tells you like other commands that start with those letters or whatever, yeah that in the events, chart editor

**Comment by ThatRozebudDude** [comment]
I don't think I'll add this but the current dev versions have a drop down list of all the events that are defined (besides stage events right now but I'll probably have it add them in the future) and you can use that to find the events that you are looking for.
