### ISSUE TITLE
PolyMod Error?

### ISSUE THREAD

**Issue by KittySleeper** [ThatRozebudDude/FPS-Plus-Public#111]
C:/Users/brand/OneDrive/Desktop/fnf/fnf code suff/FPS-Plus-Public-polymod-support/.haxelib/polymod/1,3,1/polymod/Polymod.hx:567: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/Users/brand/OneDrive/Desktop/fnf/fnf code suff/FPS-Plus-Public-polymod-support/.haxelib/polymod/1,3,1/polymod/Polymod.hx:581: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/Users/brand/OneDrive/Desktop/fnf/fnf code suff/FPS-Plus-Public-polymod-support/.haxelib/polymod/1,3,1/polymod/backends/PolymodAssets.hx:193: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/characters/ScriptableCharacter.hx:4: characters 64-94 : Type not found : polymod.hscript.HScriptedClass

**Comment by ThatRozebudDude** [comment]
Make sure you have the right version of `Polymod` installed, it should say `git` for the version. You might need to delete the `.haxelib` folder and run `hmm install` again since sometimes it will switch to the wrong version if you use hmm multiple times for some reason.
