### ISSUE TITLE
Game crashes upon exiting the caching state (6.1.0 Pre-release)

### ISSUE THREAD

**Issue by doggogit** [ThatRozebudDude/FPS-Plus-Public#120]
## Steps to reproduce
1. Open the game with a cleared save file/empty save file
2. Turn on/off whatever you want the game to cache
3. Hit ESC/Backspace

## Footage
https://github.com/user-attachments/assets/8738f55c-06ec-4f5f-b5b4-cd1c0b29d979

**Comment by ThatRozebudDude** [comment]
I am going to update the build in the pre-release with the fix for this.
