### ISSUE TITLE
Stutters during gameplay

### ISSUE THREAD

**Issue by doggogit** [ThatRozebudDude/FPS-Plus-Public#121]
## Brief description
On previous iterations of FPS+, these weird stutters during gameplay wouldn't happen, but as of the current 6.1.0 pre-release, these keep happening pretty frequently, no matter the song I'm playing.

This happens with both characters, music and graphics cached or nothing cached at all.

**Comment by ThatRozebudDude** [comment]
Are you able to provide a video of this happening? Because this doesn't seem to happen for me.

**Comment by doggogit** [comment]
> Are you able to provide a video of this happening? Because this doesn't seem to happen for me.

I'd love to, I had to sleep early last night so I forgot to reply to this, my bad

GitHub in its infinite wisdom doesn't like videos >10MB so I'll resort to Streamable

**Comment by doggogit** [comment]
[Footage with characters, graphics and music cached](https://streamable.com/9fszux)

[Footage with nothing cached](https://streamable.com/i0f3rx)

I have RTSS (RivaTuner Statistics Server) enabled and you can see spikes mid-gameplay with the frametime graph

These still occur even when I'm not recording

**Comment by ThatRozebudDude** [comment]
Interesting, I will look into it.

**Comment by ThatRozebudDude** [comment]
Do you think you could try removing `updateScoreText()` out of the `PlayState` update loop and see if that makes it run better.

**Comment by doggogit** [comment]
> Do you think you could try removing `updateScoreText()` out of the `PlayState` update loop and see if that makes it run better.

That'd require recompiling, but sure!

**Comment by doggogit** [comment]
> Do you think you could try removing `updateScoreText()` out of the `PlayState` update loop and see if that makes it run better.

Do you want me to *completely* remove the line or move it in another function?

**Comment by ThatRozebudDude** [comment]
just comment it out and see if stops the stuttering, obviously it will break the the score text but i think the stuttering might be due to the fact that the text being updated every frame

**Comment by doggogit** [comment]
> Just comment it out and see if stops the stuttering, obviously it will break the the score text but I think the stuttering might be due to the fact that the text being updated every frame. I noticed a little bit of stuttering for me occasionally and I think this helped but I'm not really sure since the stuttering didn't happen consistently for me. If this at least part of the cause I have fix for it but I just need to confirm that I will actually help.

Just in time as I'm writing my reply LOL

Okay, so, update, while commenting out the `updateScoreText()` function out of the update loop does boost my FPS by fucking 200, I think I might've found the *actual* root cause of the stutters

I noticed that it happened again, but only once or twice, and that's because the NVIDIA GPU hits 1% usage and then finds it's footing a few milliseconds after and it jumps back up to regular usage again

Below is a screenshot I took from a clip while playing Fresh Erect on the compile build with the `updateScoreText()` func commented out:
![image](https://github.com/user-attachments/assets/c43f2e94-156a-401e-8d91-ed50f627e2da)
 
Hopefully re-installing the NVIDIA GPU driver will remedy the issue

**Comment by ThatRozebudDude** [comment]
Interesting since for me commenting out the text doesn't really effect my frame rate but I'll definitely add that fix for better performance anyways since it seemed liked it helped.

**Comment by doggogit** [comment]
> Interesting since for me commenting out the text doesn't really effect my frame rate but I'll definitely add that fix for better performance anyways since it seemed liked it helped.

Comparing footage from last night, without anything cached, the framerate was ~500, and without the score text, it was peaking at like 800 and something LMAO

**Comment by ThatRozebudDude** [comment]
Just pushed a fix, lemme know if it works better when you get the chance.

**Comment by doggogit** [comment]
> Just pushed a fix, lemme know if it works better when you get the chance.

I'll try out tomorrow, hopefully that's no problem for you

**Comment by amyspark-ng** [comment]
did you try it

**Comment by doggogit** [comment]
> did you try it

I haven't, actually, been busy with college/IRL stuff, I'll try and attempt it today

**Comment by doggogit** [comment]
Huzzah! No stutters!

I think it *was* because of the corrupt integrated GPU driver that I had installed, reinstalling Windows and the driver not only fixed the issue for this version, but every other version after the polymod pre-release

Closing!

**Comment by doggogit** [comment]
> Huzzah! No stutters!
> 
> I think it _was_ because of the corrupt integrated GPU driver that I had installed, reinstalling Windows and the driver not only fixed the issue for this version, but every other version after the polymod pre-release
> 
> Closing!

Do note that performance *is* actually better now because of you changing the score update code
