### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by TheEmeraldBlade1** [ThatRozebudDude/FPS-Plus-Public#132]
I keep getting this error when I compile

C:\HaxeToolkit\haxe\std/haxe/io/Input.hx:189: characters 37-42 : Uncaught exception Eof
source/GitCommit.hx:57: characters 29-60 : Called from here
source/MainMenuState.hx:121: characters 126-150 : Called from here
C:\HaxeToolkit\haxe\std/haxe/io/Input.hx:189: characters 37-42 : For optional function argument 'Text'
source/freeplay/FreeplayState.hx:618: characters 126-150 : [WARN] Could not determine current git commit; is this a proper Git repository?
source/freeplay/FreeplayState.hx:618: characters 126-150 : [WARN] Could not determine current git commit; is this a proper Git repository?
C:\HaxeToolkit\haxe\std/haxe/io/Input.hx:189: characters 37-42 : Uncaught exception Eof
source/GitCommit.hx:57: characters 29-60 : Called from here
source/freeplay/FreeplayState.hx:618: characters 126-150 : Called from here
C:\HaxeToolkit\haxe\std/haxe/io/Input.hx:189: characters 37-42 : For optional function argument 'Text'
source/Character.hx:461: characters 10-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)

**Comment by ThatRozebudDude** [comment]
I think the issue should be fixed now, if it still doesn't work re-open this.

**Comment by TheEmeraldBlade1** [comment]
it works now thanks!
