### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by Enchantedbooz** [ThatRozebudDude/FPS-Plus-Public#137]
C:/Users/??/OneDrive/Desktop/fnf engine/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/polymod/git/polymod/hscript/_internal/PolymodAbstractScriptClass.hx:5: characters 37-55 : Type not found : PolymodScriptClass

**Comment by ThatRozebudDude** [comment]
Try reinstalling the deleting the .haxelib folder and reinstalling the libraries with hmm.
