### ISSUE TITLE
Compiling Issues 

### ISSUE THREAD

**Issue by Enchantedbooz** [ThatRozebudDude/FPS-Plus-Public#138]
C:/Users/??/OneDrive/Desktop/fnf engine/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/polymod/git/polymod/hscript/_internal/PolymodAbstractScriptClass.hx:5: characters 37-55 : Type not found : PolymodScriptClass

**Comment by moxie-coder** [comment]
you already made this issue here #137
