### ISSUE TITLE
Can Compiling FPS Plus Public

### ISSUE THREAD

**Issue by ModdingGaming10** [ThatRozebudDude/FPS-Plus-Public#139]
i can Compiling FPS-Plus-Public because of this error 

C:/Users/OneDrive/Desktop/FNF/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/polymod/git/polymod/hscript/_internal/PolymodAbstractScriptClass.hx:5: characters 37-55 : Type not found : PolymodScriptClass

someone please help me

**Comment by moxie-coder** [comment]
duplicate of #137

**Comment by ModdingGaming10** [comment]
i not see how to fix the Issue 

> duplicate of #137

i not see how to fix the Issue

**Comment by ThatRozebudDude** [comment]
Try reinstalling the deleting the `.haxelib` and reinstalling them with hmm

**Comment by ModdingGaming10** [comment]
i got C:/Users/???/OneDrive/Desktop/fnf engine/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/polymod/git/polymod/hscript/_internal/PolymodAbstractScriptClass.hx:5: characters 37-55 : Type not found : PolymodScriptClass

**Comment by moxie-coder** [comment]
maybe don’t try to compile in OneDrive? You know just as a heads up

**Comment by ModdingGaming10** [comment]
i can try

**Comment by ModdingGaming10** [comment]
i got 
source/modding/GlobalScriptingTypesMacro.hx:22: Applying scripting types to ScriptedSpriteGroup
C:/Users/???/Downloads/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/flxanimate/git/flxanimate/animate/FlxElement.hx:149: characters 39-40 : Unexpected ?

**Comment by ModdingGaming10** [comment]
i can see if i can set up build tools in part 8

**Comment by ModdingGaming10** [comment]
it doesn't working

**Comment by ModdingGaming10** [comment]
it doesn't working
