### ISSUE TITLE
Exporting to HTML5

### ISSUE THREAD

**Issue by SanicBTW** [ThatRozebudDude/FPS-Plus-Public#14]
Is there any way to compile the engine to HTML5? I've been getting errors when trying to compile it to HTML5, I've been trying to find a solution and I found [this](https://community.haxe.org/t/main-hx-errors/3187) which I thought it would help me but when trying it, it would just give me a black screen, I probably have to wait more but I would like to know if exporting to HTML5 is possible, thanks.

**Comment by ThatRozebudDude** [comment]
A lot of stuff that I added ended up breaking HTML5 stuff, but I just went through and made some changes on the `master` branch and I'm pretty sure everything is HTML5 compatible now.
