### ISSUE TITLE
how to add custom playable character

### ISSUE THREAD

**Issue by sjejfhdnsjsjdn** [ThatRozebudDude/FPS-Plus-Public#141]
how to add custom playable character?
want to add my own playable character with modpack

**Comment by SwickTheGreat** [comment]
> how to add custom playable character? want to add my own playable character with modpack

https://github.com/ThatRozebudDude/FPS-Plus-Public/wiki/Creating-a-New-Character

**Comment by sjejfhdnsjsjdn** [comment]
> > how to add custom playable character? want to add my own playable character with modpack
> 
> https://github.com/ThatRozebudDude/FPS-Plus-Public/wiki/Creating-a-New-Character

i mean character with his own remixes

**Comment by ThatRozebudDude** [comment]
There currently aren't any pages on the wiki for that but you can look in `assets/data/freeplay` and `assets/data/characterSelect` to reference how those are made. Also as of right now both Freeplay characters and Character Select characters must be a texture atlas and not a sprite sheet.
