### ISSUE TITLE
Cant edit Keybinds on Keyboard 

### ISSUE THREAD

**Issue by WillGamer803** [ThatRozebudDude/FPS-Plus-Public#144]
Hi, I have a keyboard and would like to play using it in Mobile. But I can't edit the Keybinds. It would be great if you could fix this so I can have the best experience possible with this engine.

**Comment by WillGamer803** [comment]
> Hi, I have a keyboard and would like to play using it on Mobile. But I can't edit the Keybinds. It would be great if you could fix this so I can have the best experience possible with this engine.

**Comment by WillGamer803** [comment]
> Hi, I have a keyboard and would like to play using it in Mobile. But I can't edit the Keybinds. It would be great if you could fix this so I can have the best experience possible with this engine.

**Comment by moxie-coder** [comment]
> Hi, I have a keyboard and would like to play using it in Mobile. But I can't edit the Keybinds. It would be great if you could fix this so I can have the best experience possible with this engine.

this isn’t the right repo for mobile issues
