### ISSUE TITLE
Eggnog Erect/Nightmare Crash

### ISSUE THREAD

**Issue by WillGamer803** [ThatRozebudDude/FPS-Plus-Public#146]
The game freeze on the end of music, then needs Christmas dead cutscene.

**Comment by ThatRozebudDude** [comment]
I actually just fixed this a few days ago in [this commit](https://github.com/ThatRozebudDude/FPS-Plus-Public/commit/7ee0d5934bba18ba2ac9a7225e3aee7f37c73f86), it's just not in a release version yet.

**Comment by WillGamer803** [comment]
Oh too good.

**Comment by ThatRozebudDude** [comment]
If you wanted to fix it on your end you should just be able to download [this file](https://github.com/ThatRozebudDude/FPS-Plus-Public/blob/master/assets/data/cutscenes/SantaDies.hxc) and replace the one in `assets/data/cutscenes/` and I believe it should just work.
