### ISSUE TITLE
Error: source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance

### ISSUE THREAD

**Issue by MaiBatchis** [ThatRozebudDude/FPS-Plus-Public#18]
So... I try to build the game but this error appears: "source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance", could someone help me, please? TT

**Comment by ThatRozebudDude** [comment]
use master branch

**Comment by MaiBatchis** [comment]
> use master branch

What is "Master Branch", and where can I get it? "^^

**Comment by ThatRozebudDude** [comment]
![image](https://user-images.githubusercontent.com/35246975/135868036-ebf59ec8-b837-4a03-a909-516809d47220.png)
![image](https://user-images.githubusercontent.com/35246975/135868055-0fe222da-d9c3-4246-b380-e9e76da27a85.png)

**Comment by MaiBatchis** [comment]
Thanks Roze! ^

![](file:///C:/Users/MaiBatchis/Desktop/Archivos/Colegio/W.I.P/Ilustraci%C3%B3n.jpg)
^

**Comment by MaiBatchis** [comment]
Thanks Roze ^^

![Ilustración](https://user-images.githubusercontent.com/91618548/135884361-b4e7cd74-b44c-4342-ac56-27c8155aecc3.jpg)
