### ISSUE TITLE
held notes are really buggy on primarily held note songs

### ISSUE THREAD

**Issue by bubsuki** [ThatRozebudDude/FPS-Plus-Public#23]
If playing a song that has mostly held notes in the entire song they'll just not be hit half the time when you try to hit them regardless of the timing or any of that, is starting to become incredibly annoying (sorry if this isn't something that should be posted here)

**Comment by ThatRozebudDude** [comment]
Are you able to provide any more details?

**Comment by bubsuki** [comment]
All I can really say is that we had a song where nearly every note was held notes nonstop (and long ones at that) and for some reason the input didn't like that. Half the time trying to hit the next note would just immediately make you miss regardless of timing, and held notes would start getting to the point where they would count as a miss unless you held them seconds after they had already ran out. I would try to figure it out myself but unfortunately I'm not exactly an expert Haxe coder just yet so I thought I'd leave a post

**Comment by bubsuki** [comment]
new input fixed this
