### ISSUE TITLE
Type "System" not found when compiling

### ISSUE THREAD

**Issue by DarkMinerULTRA** [ThatRozebudDude/FPS-Plus-Public#29]
when i compile it says this:

source/title/TitleScreen.hx:116: characters 4-10 : Type not found : System

My OS is MacOS, my OS version is 10.13.6, and my Haxe version is 4.1.5.
Can someone help with this

**Comment by RoxDivision231** [comment]
Hey under import openfl.Assets; add import openfl.system.System;

welcome
