### ISSUE TITLE
Week 6 - Dialogue doesn't advance with Xbox 360 inputs

### ISSUE THREAD

**Issue by Punkinator7** [ThatRozebudDude/FPS-Plus-Public#3]
I played through the first 6 weeks with an Xbox controller and the menus, in game controls and such was working fine, except when I started week 6 I tried pushing every button on that controller and none of them advanced the dialogue with senpai, so I had to use a keyboard for that. its a Xbox 360 blue rock candy controller (the one with a non removable wire, cause the newer ones use a detachable cable)

**Comment by ThatRozebudDude** [comment]
I forgot to add a case for controller in the dialogue state. I'll add it for the next update.
