### ISSUE TITLE
Just two things.

### ISSUE THREAD

**Issue by Joalor64GH** [ThatRozebudDude/FPS-Plus-Public#32]
1: Can you make workflows?
2. Can you make this repo a public template?

**Comment by itsDARK768** [comment]
I know I am not the creator of this rep but its not going to happen, this rep has not been touched even since like, july 18th

**Comment by Joalor64GH** [comment]
oh okay

**Comment by MemeHoovy** [comment]
I know that this is necroposting but I need to get this out, rozebud has started being active here again, so _maybe_ he will add this kind of shit you requested
