### ISSUE TITLE
error while compiling FPSplus

### ISSUE THREAD

**Issue by teh404guy** [ThatRozebudDude/FPS-Plus-Public#4]
source/ConfigMenu.hx:479: characters 111-121 : Unknown identifier : inputValue
source/ConfigMenu.hx:479: characters 111-121 : ... For function argument 'noteGlowW'

**Comment by FelipeBacana** [comment]
Yeah i have the same error while compiling it appears that something gone wrong

**Comment by FelipeBacana** [comment]
> source/ConfigMenu.hx:479: characters 111-121 : Unknown identifier : inputValue
> source/ConfigMenu.hx:479: characters 111-121 : ... For function argument 'noteGlowW'

I think i know what's the problem the creator forgot to put input Value in "config" file

**Comment by BTTRG** [comment]
I get the same error. Sigh, I guess I won't be using FPS Plus for my mod...

**Comment by ThatRozebudDude** [comment]
I can't seem to replicate this issue. Both the release and master branches compile fine for me.

**Comment by teh404guy** [comment]
Did you try compiling in a fresh linux container?
Since i used a container to try and build mine
The new version doesnt compile at all
But the old release does

**Comment by ThatRozebudDude** [comment]
Okay, I found this issue. It only happens when compiling with -debug. In _ConfigMenu.hx_ there is a section that starts with `#if debug`. You can just remove that section. I'll fix it and push the update to master as well as a hotfix for the release branch.
