### ISSUE TITLE
Cannot access static field SKIP_STEP_LIMIT from a class instance

### ISSUE THREAD

**Issue by Slyshii** [ThatRozebudDude/FPS-Plus-Public#5]
After the update that no longer uses rozebud's fork of the webm extension, I get an issue with compiling the game even after reinstalling the correct extension and doing "lime rebuild extension-webm windows".

Building the game with "lime test windows" is immediately halted with the following error:

source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance

**Comment by ThatRozebudDude** [comment]
Did you rebuild the extension after switching to GWebDev's version?

**Comment by XaraKuma** [comment]
I'm having the same problem as well, after I switched the extension to gwebdev's version I got:

"You already have extension-webm version git installed.
Updating extension-webm version git ...
extension-webm was updated
Library extension-webm current version is now git"

and when using "lime rebuild extension-webm windows" I didn't get sent back any kind of message or error. when using "lime test windows" it still gives me the error message 
"source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance"

**Comment by ThatRozebudDude** [comment]
I'm not sure what's happening then, because SKIP_STEP_LIMIT is only static in older versions or extension-webm. Maybe try manually deleting it from haxelib and re-installing it?

**Comment by YoshiPL23** [comment]
actually, if you still have this SKIP_STEP_LIMIT then there are 2 ways to avoid this error
1.install the kade engine extension-webm fork
2.delete GlobalVideo.getWebm().webm.SKIP_STEP_LIMIT = frameSkipLimit; text (its in 48 line)
and will problably work!

well for me it did

**Comment by gummybear17** [comment]
i made a video about it and how to [fix it ](https://www.youtube.com/watch?v=4fFx5iqOPcA) 
this is not a self promo
