### ISSUE TITLE
camera zoom broke i think 

### ISSUE THREAD

**Issue by Pogtoaster** [ThatRozebudDude/FPS-Plus-Public#51]
i decided to build the engine and check out the new stuff that way (as i thought it would be more fun) and when i loaded pico, i was greeted by the void, i didn't edit any of the source ether (image of the issue) [https://media.discordapp.net/attachments/1069046584303685643/1092599314565582848/image.png?width=1115&height=630](url)

**Comment by SanicBTW** [comment]
Check your flixel version

**Comment by Pogtoaster** [comment]
4.0.2 i think, thats what command prompt says at least

**Comment by SanicBTW** [comment]
update to 5.2.2 (haxelib install flixel 5.2.2)

**Comment by Pogtoaster** [comment]
it works thank you!

**Comment by SanicBTW** [comment]
> it works thank you!

you're welcome!!
