### ISSUE TITLE
FPS Plus Fresh Compiled: Week 7 Zooming Issue

### ISSUE THREAD

**Issue by Electr0Gunner** [ThatRozebudDude/FPS-Plus-Public#54]
In a compiled FPS Plus build 4.0.1
In week 7 there is a zooming issue with everything (Ui Stage etc.)

https://github.com/ThatRozebudDude/FPS-Plus-Public/assets/114804446/07bff5c1-6cab-4d58-b797-dbc6693a12fb

**Comment by Electr0Gunner** [comment]
Also on Guns and Stress
i just forgot to record them

**Comment by Electr0Gunner** [comment]
in the github compiled build
it uses video files so it does not have an issue there

**Comment by altdude22** [comment]
ruh oh shraggy

**Comment by ThatRozebudDude** [comment]
I think it's an issue with the version of Flixel that you're using. The newest version of Flixel removes the zoom argument when creating an FlxGame.

**Comment by SanicBTW** [comment]
Not really, maybe its flixel-addons
