### ISSUE TITLE
[Suggestion / Enhancement] Source Folder organization

### ISSUE THREAD

**Issue by crowplexus** [ThatRozebudDude/FPS-Plus-Public#59]
one minor thing I really wish FPS+ had was a organized source folder

it's nothing really big, but makes navigation slightly easier, although takes some time getting used to (which by then you can just press Ctrl+P on VSCode and put the name of the file you wanna go so it takes you there faster than the folder explorer)

**Comment by GhostBnuuy** [comment]
![1170630864758132837](https://github.com/ThatRozebudDude/FPS-Plus-Public/assets/84008574/115cd58b-dbd4-4db2-88e5-c3f59a1c67bf)

**Comment by BlueColorsin** [comment]
Rosebud I beg, it will make the engine like 20 times better

because 
# UGLY
![NVIDIA_Share_Ew4sK0GGX0](https://github.com/ThatRozebudDude/FPS-Plus-Public/assets/76269429/58685f65-288a-4026-b0e2-a04cb8d37198)

**Comment by ThatRozebudDude** [comment]
I will live my life the way I want. I am a free man.
