### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by JeremyCodes08** [ThatRozebudDude/FPS-Plus-Public#60]
![image](https://github.com/ThatRozebudDude/FPS-Plus-Public/assets/117064691/21b0e28e-f84f-43dc-a944-6b3e05bf83d8)
(part 1)
![image](https://github.com/ThatRozebudDude/FPS-Plus-Public/assets/117064691/4b07d237-1a30-49c3-8d17-83a4be9bdcb7)
(part 2)
![image](https://github.com/ThatRozebudDude/FPS-Plus-Public/assets/117064691/6b586bc2-3b42-42e0-bf3e-963d363c9646)
(part 3)

**Comment by ThatRozebudDude** [comment]
I'm gonna need some more info. It could be an issue with the version of Flixel that you are using since you are also getting errors in some of the Flixel addon libraries.
