### ISSUE TITLE
[SUGGESTION] Replace the current video player with `hxvlc` or `hxCodec`(?)

### ISSUE THREAD

**Issue by doggogit** [ThatRozebudDude/FPS-Plus-Public#61]
I believe that `hxCodec` and `hxvlc` are now the new standard for playing videos in flixel projects, so, why not have this mod framework use one of the two?

You can check them out here:
- `hxvlc` -> [Haxe library](https://lib.haxe.org/p/hxvlc), [GitHub repo](https://github.com/MAJigsaw77/hxvlc)
- `hxCodec` -> [Haxe library](https://lib.haxe.org/p/hxCodec), [GitHub repo](https://github.com/polybiusproxy/hxCodec)

I'd understand if you believe that the current method is more than good enough and close this.

**Comment by ThatRozebudDude** [comment]
I will look into it.

**Comment by ThatRozebudDude** [comment]
I've decided to keep the video playback system the same for now.

**Comment by doggogit** [comment]
> I've decided to keep the video playback system the same for now.

Alright, best of luck with future endeavors :)
