### ISSUE TITLE
Issue with compiling

### ISSUE THREAD

**Issue by billyhilly-cowsay** [ThatRozebudDude/FPS-Plus-Public#62]
I am attempting to compile FPS Plus, and I keep getting this error:

C:/HaxeToolkit/haxe/lib/flixel/5,5,0/flixel/graphics/frames/FlxAtlasFrames.hx:86: characters 19-21 : Expected )

Is there any way to fix this error?

**Comment by ThatRozebudDude** [comment]
Are your Flixel libraries up to date?
