### ISSUE TITLE
funny compile

### ISSUE THREAD

**Issue by itsaban** [ThatRozebudDude/FPS-Plus-Public#7]
```
source/Main.hx:3: characters 8-23 : Type not found : webm.WebmPlayer
source/Main.hx:20: characters 41-45 : Accessing this field requires a system platform (php,neko,cpp,etc.)``
```

it so funny because i just downloaded source code and don't touch main.hx. only character.hx was edited. help me please

**Comment by itsaban** [comment]
line three is import
line twenty is empty

**Comment by teh404guy** [comment]
go to main, looks for soemthing that starts with SKIP
remove that line

**Comment by SanicBTW** [comment]
This is happening to me when exporting to HTML5, I tried to search for some help, found a haxeflixel forum post that had some way into fixing it but nothing really happened as it would throw more errors

**Comment by ThatRozebudDude** [comment]
A lot of stuff that I added ended up breaking HTML5 stuff, but I just went through and made some changes on the `master` branch and I'm pretty sure everything is HTML5 compatible now.
