### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Bboaa** [ThatRozebudDude/FPS-Plus-Public#76]
tried to compile the new version of fps plus and got this errors, i already downloaded funkinCrew's flxanimate btw

source/AtlasSprite.hx:29: characters 14-22 : flxanimate.animate.FlxAnim has no field callback
source/AtlasSprite.hx:42: characters 29-34 : String should be flxanimate.animate.FlxKeyFrame
source/AtlasSprite.hx:42: characters 29-34 : ... For function argument 'x'
source/AtlasSprite.hx:50: characters 21-26 : String should be flxanimate.animate.FlxKeyFrame
source/AtlasSprite.hx:50: characters 21-26 : ... For function argument 'x'

**Comment by PipocaAventuras** [comment]
im having this error and more:

source/Character.hx:400: characters 10-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)

**Comment by moxie-coder** [comment]
that’s not an error

**Comment by PipocaAventuras** [comment]
a
