### ISSUE TITLE
compiling issue 

### ISSUE THREAD

**Issue by Bezizeja** [ThatRozebudDude/FPS-Plus-Public#77]
i tried re-installing haxeflixel multiple times and funkin's flxanimate library its spits out this (release branch)

C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/animate/FlxAnim.hx:26: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/FlxAnimate.hx:331: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/HaxeToolkit/haxe/lib/flixel/5,8,0/flixel/graphics/frames/FlxAtlasFrames.hx:472: characters 18-24 : ... Base field is defined here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/AtlasSprite.hx:29: characters 14-22 : flxanimate.animate.FlxAnim has no field callback
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Character.hx:400: characters 10-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)

**Comment by Bezizeja** [comment]
idk i might be missing something

**Comment by ThatRozebudDude** [comment]
Make sure that the FunkinCrew version of flxanimate is actually being used. You can see by the logs that it's trying to use `3.0.4` from haxelib instead of the FunkinCrew version, which should be `git`.

**Comment by Bezizeja** [comment]
progress still missing something
C:\Users\Janis\Desktop\FPS-Plus-Public-experimental>lime test windows -release
C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/AtlasSprite.hx:29: characters 14-22 : flxanimate.animate.FlxAnim has no field callback
source/AtlasSprite.hx:42: characters 29-34 : String should be flxanimate.animate.FlxKeyFrame
source/AtlasSprite.hx:42: characters 29-34 : ... For function argument 'x'
source/AtlasSprite.hx:50: characters 21-26 : String should be flxanimate.animate.FlxKeyFrame
source/AtlasSprite.hx:50: characters 21-26 : ... For function argument 'x'
C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Character.hx:400: characters 10-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
