### ISSUE TITLE
Compiling Error Character

### ISSUE THREAD

**Issue by Limakoko** [ThatRozebudDude/FPS-Plus-Public#78]
lol an error again, I not a coder but im working with a friend in my computer, so i tried to fix this error.

C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/animate/FlxAnim.hx:25: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/FlxAnimate.hx:502: characters 97-105 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/AtlasSprite.hx:29: characters 14-22 : flxanimate.animate.FlxAnim has no field callback
source/AtlasSprite.hx:42: characters 29-34 : String should be flxanimate.animate.FlxKeyFrame
source/AtlasSprite.hx:42: characters 29-34 : ... For function argument 'x'
source/AtlasSprite.hx:50: characters 21-26 : String should be flxanimate.animate.FlxKeyFrame
source/AtlasSprite.hx:50: characters 21-26 : ... For function argument 'x'
C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:16: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSoundC:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/animate/ButtonEvent.hx:23: characters 51-59 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSoundsource/Character.hx:400: characters 10-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)

**Comment by Bezizeja** [comment]
i have the same issues even tho i have all the latest libraries installed and latest haxe
