### ISSUE TITLE
Enhancement for RAM Usage

### ISSUE THREAD

**Issue by KlutchDj** [ThatRozebudDude/FPS-Plus-Public#8]
After playing some of the FPS+ , ive realized that it was taking massive amount of my RAM . almost max at 5 gigs of ram at that. And im assuming its mostly because of precaching all of the assets,songs,data etc etc that enabled faster loads speeds.. which makes sense , but it also takes a huge storage of my ram at the same time . And a solution to this is by having a option that allows the player to decide of what the game wants to cache at start up. so if the player wants to cache only characters or songs , the player would only set it at caching songs only. like a filter if that makes sense. Heres a video that shows the amount of ram that it uses while playing a song. 

https://user-images.githubusercontent.com/81717689/128137227-74587740-0506-4831-af19-b1ff883fa545.mp4

**Comment by ThatRozebudDude** [comment]
I might add some options in-game some time in the future, but you can use `-skipsound`, `-skipcharacters`, and `-skipgraphics` as launch arguments to disable caching certain items.
