### ISSUE TITLE
Invalid Field: Rank

### ISSUE THREAD

**Issue by Bboaa** [ThatRozebudDude/FPS-Plus-Public#85]
i keep getting this error every time i open the game i tried to compile it instead of using the released build and it keeps crashing
![imagem_2024-08-03_164322372](https://github.com/user-attachments/assets/03f97a0f-cfaf-432b-8c1f-77ff25e7a988)

**Comment by ThatRozebudDude** [comment]
Can you send your score save data? It should be located in `AppData\Roaming\Rozebud\FunkinFPSPlus\Rozebud.FunkinFPSPlus`. I think I might know what's causing it but I'd need to see your save data to verify it since I can't replicate the issue.

**Comment by Bboaa** [comment]
[scores.zip](https://github.com/user-attachments/files/16482862/scores.zip)
here

**Comment by ThatRozebudDude** [comment]
I just fixed it in [this commit](https://github.com/ThatRozebudDude/FPS-Plus-Public/commit/b6939c324c3d5ad96cd81b154804d4e29654f2e8). If you compile the game and run it your save file should be automatically fixed and it should also start working on the release build of the game as well.
