### ISSUE TITLE
[BUG?] results screen error

### ISSUE THREAD

**Issue by 7oltan** [ThatRozebudDude/FPS-Plus-Public#86]
the "normal" song (good and great) doesnt have an intro it just uses the "excellent" music instead

**Comment by ThatRozebudDude** [comment]
This is intended behavior. The results screen uses the excellent intro for every rank while it's counting the score.

**Comment by 7oltan** [comment]
> This is intended behavior. The results screen uses the excellent intro for every rank while it's counting the score.

oh-
