### ISSUE TITLE
having trouble compiling theres an isssue with weekend 1's stage

### ISSUE THREAD

**Issue by 504brandon** [ThatRozebudDude/FPS-Plus-Public#88]
hey im having an issue compiling, its related to A-Bot

source/stages/elements/ABotVisualizer.hx:19: characters 16-32 : Type not found : SpectralAnalyzer

**Comment by ThatRozebudDude** [comment]
Is funkin.vis installed correctly?

**Comment by 504brandon** [comment]
i mean how would i install it incorrectly-

**Comment by ThatRozebudDude** [comment]
I don't know, but clearly it's having trouble finding SpectralAnalyzer and I've had problems with it not installing correctly before.

**Comment by doggogit** [comment]
I believe running `hmm reinstall -f` should reupdate/reinstall most libs, try running that and attempt to recompile
