### ISSUE TITLE
Results "loss" animation doesn't loop 

### ISSUE THREAD

**Issue by NoNamesInStock** [ThatRozebudDude/FPS-Plus-Public#89]
the animation that plays for getting the lowest rank doesn't loop like in the original game, though that seems to be it. (tested on Tutorial and Roses Erect)

https://github.com/user-attachments/assets/bc1d8f7a-8abb-4c9a-80c3-c1393a32cd2f

**Comment by ThatRozebudDude** [comment]
I just fixed it in [this commit](https://github.com/ThatRozebudDude/FPS-Plus-Public/commit/c136fd4afdfa9ada32f2538846e0bf117d7b46c4). I'm pretty sure the animation used to loop fine but broke when I added a fix for other animations looping early.
