### ISSUE TITLE
Solution to `Could not find haxelib "hxCodec", does it need to be installed?`

### ISSUE THREAD

**Issue by doggogit** [ThatRozebudDude/FPS-Plus-Public#91]
For anyone new here trying to compile FPS+, after running `hmm install`,  there is a high chance that the following error will appear:

![image](https://github.com/user-attachments/assets/2980b351-cb8b-46b7-9575-ba5a0c75b2d9)

The solution to this is simple, just install `hxCodec` globally by running the following command:
> (Whenever the commit hash (the huge string of numbers at letters at the end of the command) gets updated, I'll update it here)
```
haxelib --global git hxCodec https://github.com/FunkinCrew/hxCodec 61b98a7a353b7f529a8fec84ed9afc919a2dffdd
```

After the install completes, you should be able to compile!

**Comment by doggogit** [comment]
@ThatRozebudDude if you could close the discussion and pin the issue so people know just in case 👍

**Comment by ThatRozebudDude** [comment]
I wonder if there is a way to fix this because I've also had this problem with hxvlc and it's really annoying.

**Comment by doggogit** [comment]
> I wonder if there is a way to fix this because I've also had this problem with hxvlc and it's really annoying.

It's something to do with the lib, I'm not sure exactly what

**Comment by doggogit** [comment]
@ThatRozebudDude I've noticed that the `develop` branch for base Funkin' has this issue fixed, but it happens on every other repository. The commit hash remains the same on this repo and Funkin', really weird, might have to ask around and see if I can get this fixed here too..

**Comment by ThatRozebudDude** [comment]
Did you check that it's actually fixed by removing the library from your global haxelib?

**Comment by doggogit** [comment]
> Did you check that it's actually fixed by removing the library from your global haxelib?

Yeah, I removed `hxCodec` entirely and it worked for Funkin', doesn't seem to work here though.

I tried it on my laptop where I had to install Haxe from scratch, Funkin' `develop` just works without needing to install hxCodec globally...

**Comment by doggogit** [comment]
@ThatRozebudDude sorry for the ping, yet again, but potential lead!

me and a friend think it's due to some flag that's causing the error to appear, I have a PR ready for another haxelib package manager that's called HxPKG but it still reports that the lib is missing

switching package managers will most likely be required once we get this sorted as `hmm` hasn't been updated in quite a while

**Comment by ThatRozebudDude** [comment]
I don't know why switching package managers would be necessary because Funkin still uses hmm, right? Also what do you mean by "some flag"?

**Comment by CobaltBar** [comment]
the curse of hxCodec

**Comment by CobaltBar** [comment]
okay it straight up doesn't work with local repos
you have to install it globally
