### ISSUE TITLE
Charts are outdated

### ISSUE THREAD

**Issue by biomseed** [ThatRozebudDude/FPS-Plus-Public#93]
Various charts from the game (not limited to erect songs) have been updated in v0.4 of the base game. FPS Plus does not have these charts. 
Charts updated in the base game according to the changelog are:

  - Tutorial (increased the note speed slightly)
  - Spookeez
  - Monster
  - Winter Horrorland
  - M.I.L.F.
  - Senpai (increased the note speed)
  - Roses
  - Thorns (increased the note speed slightly)
  - Ugh
  - Stress
  - Lit Up

Some of these apply to BOTH Erect variations and the regular variation.
Some charts have changes that add missing notes to the chart (like with Monster's), but can also have certain missing notes in them (also Monster).

**Comment by ThatRozebudDude** [comment]
I have been thinking about importing the new charts into the game, it's just that it takes a bit of time to clean them up and get everything working properly due to the base game charts now being a wildly different format. I will get around to this eventually.

**Comment by biomseed** [comment]
I don't think Monster got updated with them all
