### ISSUE TITLE
Compiling error.

### ISSUE THREAD

**Issue by Snowy-0** [ThatRozebudDude/FPS-Plus-Public#96]
I've been trying to compile FPS Plus since last night, yet it keeps stopping midway through and gives me what I assume is an error. I have everything installed correctly I believed, and even reinstalled all of my libraries to be sure. I don't know if this is something on my end I'm missing.

source/note/Note.hx:120: characters 10-15 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:120: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/note/Note.hx:127: characters 11-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:127: characters 11-16 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/note/Note.hx:148: characters 10-15 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:148: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/note/Note.hx:154: characters 10-15 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:154: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/AtlasSprite.hx:34: characters 14-21 : flxanimate.animate.FlxAnim has no field onFrame
source/AtlasSprite.hx:48: characters 72-76 : Null<String> has no field name
source/Character.hx:455: characters 10-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/AtlasSprite.hx:104: characters 72-76 : Null<String> has no field name
source/PlayState.hx:1039: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/PlayState.hx:1046: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/PlayState.hx:1053: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/AtlasSprite.hx:193: characters 14-20 : flxanimate.animate.FlxAnim has no field resume
source/AtlasSprite.hx:239: characters 40-47 : flixel.math.FlxMatrix should be Int
source/AtlasSprite.hx:239: characters 40-47 : ... For function argument 'curFrame'
source/AtlasSprite.hx:247: characters 9-18 : Unknown identifier : relativeX
source/AtlasSprite.hx:248: characters 9-18 : Unknown identifier : relativeY
source/AtlasSprite.hx:251: characters 132-139 : Array<flixel.FlxCamera> should be Null<openfl.geom.ColorTransform>
source/AtlasSprite.hx:251: characters 132-139 : ... For optional function argument 'colorTransform'
source/AtlasSprite.hx:252: characters 22-32 : Unknown identifier : _indicator
source/AtlasSprite.hx:252: characters 22-32 : ... For function argument 'limb'

**Comment by ThatRozebudDude** [comment]
Did you use hmm to install the libraries?

**Comment by Snowy-0** [comment]
Yeah, I did. And even to be sure again, I just retried using hmm to reinstall/update them. Still gives the same error.

**Comment by ThatRozebudDude** [comment]
I've had some trouble with hmm when updating or changing version of certain libraries. Try deleting the `.haxelib` and just running `hmm install` and re-installing everything.

**Comment by Snowy-0** [comment]
I think that did it, the game's actually compiling now. Thanks!
