### ISSUE TITLE
Use `moonchart` for chart conversion

### ISSUE THREAD

**Issue by doggogit** [ThatRozebudDude/FPS-Plus-Public#97]
I know that you've made your own Python script that converts charts to and from V-Slice to FPS+, but, I think it's still worth checking out `moonchart` ([haxelib link](https://lib.haxe.org/p/moonchart/), [GitHub repo](https://github.com/MaybeMaru/moonchart)), as you can also embed code within FPS+ itself so it automatically does the conversion without any user input.

Of course, you can just make a script outside of FPS+ and convert the charts that way, but, the former exists, so... :p

**Comment by MaybeMaru** [comment]
Hey there, the FPS+ format is still a bit underdeveloped in moonchart but if this actually get used I'd be happy to improve it and help with any other issues that may run in the process of implementing it. You can contact me in Discord as `maybemaru`.

What moonchart basically does is have a bunch of parsers for lots of formats that can convert to a basic format that then can be converted back to any other format. So it opens the door for support of FNF charts like Vslice, Legacy, Psych, Kade and from other rhythm games like Osu!Mania, Quaver or Stepmania. It's completely understandable if it's not part of the engine's goals to support all of these formats though.

**Comment by doggogit** [comment]
> Hey there, the FPS+ format is still a bit underdeveloped in moonchart but if this actually get used I'd be happy to improve it and help with any other issues that may run in the process of implementing it. You can contact me in Discord as `maybemaru`.
> 
> What moonchart basically does is have a bunch of parsers for lots of formats that can convert to a basic format that then can be converted back to any other format. So it opens the door for support of FNF charts like Vslice, Legacy, Psych, Kade and from other rhythm games like Osu!Mania, Quaver or Stepmania. It's completely understandable if it's not part of the engine's goals to support all of these formats though.

Yeah, I forgot to mention, FPS+ isn't the *only* supported format, there's a lot of formats from different engines and even different *rhythm games*!

**Comment by ThatRozebudDude** [comment]
I don't really plan to have chart conversion as something in-game, the script is mostly just to help with importing charts from base game whenever there's an update or something. I will keep this in mind if this is ever something I wanna do though.

**Comment by doggogit** [comment]
> I don't really plan to have chart conversion as something in-game, the script is mostly just to help with importing charts from base game whenever there's an update or something. I will keep this in mind if this is ever something I wanna do though.

Alrighty!
